### ISSUE TITLE
[Documentation] Broker socket not found - flux not started 

### ISSUE THREAD

**Issue by samwaseda** [pyiron/executorlib#403]
I saw this example in the notebook:

```python
import flux.job
from executorlib import Executor

with flux.job.FluxExecutor() as flux_exe:
    with Executor(max_cores=1, flux_executor=flux_exe) as exe:
        future = exe.submit(sum, [1, 1])
        print(future.result())
```

But on two different servers I got the following error:

```python
     67         if errmsg:
     68             msg += f": {errmsg}"
---> 69         raise OSError(err.errno, msg)
     71 self.aux_txn = None
     72 self._active_watchers = set()

FileNotFoundError: [Errno 2] Unable to connect to Flux: broker socket /run/flux/local was not found
```

How can I make it run?

**Comment by jan-janssen** [comment]
You have to start flux before you can use it. Either by calling `flux start` before you call `jupyter notebook` or by modifying you jupyter kernel. Like the one in https://github.com/pyiron/executorlib/blob/main/binder/kernel.json . This issue was previously reported in https://github.com/pyiron/executorlib/issues/375 . I try to work on it next week to make this part more clear in the documentation.

**Comment by samwaseda** [comment]
ah right we had this stuff. Sorry for the repetition
