### ISSUE TITLE
[bug] Spurious CPU usage with PoolExecutor

### ISSUE THREAD

**Issue by pmrv** [pyiron/executorlib#95]
Using `PoolExecutor` incurs strangely high CPU usage.  The MWE below shows 40% cpu on both the process that runs it as well as the `mpipool.py` process spawned in the background. After the futures are ready the main process blocks a full core until the executor shuts down. It sounds as if processes are spinning on the ZMQ socket or there are extra messages sent back and forth all the time, because I can make the CPU usage go down while the futures are running by adding sleeps or prints into the main loop of `mpipool.py`.  CPU usage remains high until the executor shuts down though even in that case.  I haven't figured out yet how to monitor the ZMQ socket though, so I cannot confirm that hypothesis.

Using the `ProcessPoolExecutor` from the standard library this does not happen.

```python
import time
from pympipool import PoolExecutor

def calc(n):
    time.sleep(30)
    return n**2

exe = PoolExecutor(max_workers=4)
f1 = exe.submit(calc, 42)
f2 = exe.submit(calc, 84)
f1.add_done_callback(print)
f2.add_done_callback(print)
time.sleep(60)  # workaround #94 
exe.shutdown(wait=True)
```

**Comment by jan-janssen** [comment]
@pmrv While I am still looking into #94 Can you check if the CPU load is decreased when applying https://github.com/pyiron/pympipool/pull/98 ?

**Comment by jan-janssen** [comment]
The issue is the continuous synchronization of the futures objects between the serial python process and the MPI parallel python process. This is now moved to a single function https://github.com/pyiron/pympipool/blob/main/pympipool/share/serial.py#L140 still the issue remains, this function is called very frequently. The background is that futures objects can either be cancelled by the user in the serial process or completed by the MPI parallel process. In both cases the results have to be communicated to the corresponding other process.

**Comment by jan-janssen** [comment]
@pmrv in https://github.com/pyiron/pympipool/pull/105 I added a sleep function to reduce the synchronization frequency. the default is 0.1 seconds which at least on my system does not result in a notable CPU spike. But the parameter is user adjustable to fine tune the synchronization. Can you take a look at the pull request and give me some feedback if it addresses your concerns?
